import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "./sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="flex">
        <Sidebar />
        <div className="w-full">{children}</div>
      </div>
    </html>
  );
}
